package com.ynswet.system.sc.domain;
// Generated 2015-11-27 16:40:15 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Emp generated by hbm2java
 */
@Entity
@Table(name = "emp", catalog = "fd_d1")
public class Emp implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	/**
	 * 用户内码(取自 USER表).
	 */
	private int uid;
	/**
	 * 员工编码(标准工号).
	 */
	private String empCode;
	/**
	 * 工号密码.
	 */
	private String empPassword;
	/**
	 * 员工类型(*, 0=员工, P=合作伙伴).
	 */
	private String empType;
	/**
	 * 入职时间.
	 */
	private Date entryDate;
	/**
	 * 离职时间.
	 */
	private Date departDate;
	/**
	 * 岗级(*, 0=未知, A=一般员工, B=一般管理, C=高层管理).
	 */
	private String postRank;
	/**
	 * 个人简历.
	 */
	private String resume;
	/**
	 * 父记录ID, 直接上级的UID.
	 */
	private int parentId;
	/**
	 * 状态(*, 0=正常, N=未转正, S=失效).
	 */
	private String status;
	/**
	 * 备注.
	 */
	private String note;
	/**
	 * 记录建立时间.
	 */
	private Date createTime;
	/**
	 * 最后修改时间.
	 */
	private Date modifyTime;

	public Emp() {
	}

	public Emp(int uid, String empCode, String empPassword, String empType,
			String postRank, int parentId, String status) {
		this.uid = uid;
		this.empCode = empCode;
		this.empPassword = empPassword;
		this.empType = empType;
		this.postRank = postRank;
		this.parentId = parentId;
		this.status = status;
	}
	public Emp(int uid, String empCode, String empPassword, String empType,
			Date entryDate, Date departDate, String postRank, String resume,
			int parentId, String status, String note, Date createTime,
			Date modifyTime) {
		this.uid = uid;
		this.empCode = empCode;
		this.empPassword = empPassword;
		this.empType = empType;
		this.entryDate = entryDate;
		this.departDate = departDate;
		this.postRank = postRank;
		this.resume = resume;
		this.parentId = parentId;
		this.status = status;
		this.note = note;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
	}

	@Id
	@Column(name = "UID", unique = true, nullable = false)
	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}
	@Column(name = "EMP_Code", nullable = false, length = 30)
	public String getEmpCode() {
		return this.empCode;
	}

	public void setEmpCode(String empCode) {
		this.empCode = empCode;
	}
	@Column(name = "EMP_Password", nullable = false, length = 30)
	public String getEmpPassword() {
		return this.empPassword;
	}

	public void setEmpPassword(String empPassword) {
		this.empPassword = empPassword;
	}
	@Column(name = "EMP_Type", nullable = false, length = 1)
	public String getEmpType() {
		return this.empType;
	}

	public void setEmpType(String empType) {
		this.empType = empType;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "Entry_DATE", length = 10)
	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "Depart_DATE", length = 10)
	public Date getDepartDate() {
		return this.departDate;
	}

	public void setDepartDate(Date departDate) {
		this.departDate = departDate;
	}
	@Column(name = "POST_Rank", nullable = false, length = 1)
	public String getPostRank() {
		return this.postRank;
	}

	public void setPostRank(String postRank) {
		this.postRank = postRank;
	}
	@Column(name = "Resume", length = 65535)
	public String getResume() {
		return this.resume;
	}

	public void setResume(String resume) {
		this.resume = resume;
	}
	@Column(name = "ParentID", nullable = false)
	public int getParentId() {
		return this.parentId;
	}

	public void setParentId(int parentId) {
		this.parentId = parentId;
	}
	@Column(name = "Status", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	@Column(name = "Note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Create_Time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Modify_Time", length = 19)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(" [");
		buffer.append("uid").append("='").append(getUid()).append("' ");
		buffer.append("empCode").append("='").append(getEmpCode()).append("' ");
		buffer.append("empPassword").append("='").append(getEmpPassword())
				.append("' ");
		buffer.append("empType").append("='").append(getEmpType()).append("' ");
		buffer.append("entryDate").append("='").append(getEntryDate())
				.append("' ");
		buffer.append("departDate").append("='").append(getDepartDate())
				.append("' ");
		buffer.append("postRank").append("='").append(getPostRank())
				.append("' ");
		buffer.append("resume").append("='").append(getResume()).append("' ");
		buffer.append("parentId").append("='").append(getParentId())
				.append("' ");
		buffer.append("status").append("='").append(getStatus()).append("' ");
		buffer.append("note").append("='").append(getNote()).append("' ");
		buffer.append("createTime").append("='").append(getCreateTime())
				.append("' ");
		buffer.append("modifyTime").append("='").append(getModifyTime())
				.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}
