package com.ynswet.system.sc.domain;
// Generated 2015-7-17 16:03:34 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ModifydataL generated by hbm2java
 */
@Entity
@Table(name = "modifydata_l", catalog = "fd_d1")
public class ModifydataL implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	/**
	 * 自增日志序列号.
	 */
	private Integer logId;

	/**
	 * 修改人.
	 */
	private String modifyEmp;

	/**
	 * 修改日期(手工录入的).
	 */
	private String modifyDate;

	/**
	 * 处理事件和背景简述.
	 */
	private String eventDesc;

	/**
	 * 处理规则简述.
	 */
	private String ruleDesc;

	/**
	 * 处理结果简述.
	 */
	private String reportDesc;

	/**
	 * 图文附件ID(指脚本, 数据清单等).
	 */
	private String fileUrl;

	/**
	 * 备注.
	 */
	private String note;

	/**
	 * 记录建立时间.
	 */
	private Date createTime;

	public ModifydataL() {
	}

	public ModifydataL(Date createTime) {
		this.createTime = createTime;
	}
	public ModifydataL(String modifyEmp, String modifyDate, String eventDesc,
			String ruleDesc, String reportDesc, String fileUrl, String note,
			Date createTime) {
		this.modifyEmp = modifyEmp;
		this.modifyDate = modifyDate;
		this.eventDesc = eventDesc;
		this.ruleDesc = ruleDesc;
		this.reportDesc = reportDesc;
		this.fileUrl = fileUrl;
		this.note = note;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "LogID", unique = true, nullable = false)
	public Integer getLogId() {
		return this.logId;
	}

	public void setLogId(Integer logId) {
		this.logId = logId;
	}

	@Column(name = "Modify_EMP", length = 30)
	public String getModifyEmp() {
		return this.modifyEmp;
	}

	public void setModifyEmp(String modifyEmp) {
		this.modifyEmp = modifyEmp;
	}

	@Column(name = "Modify_Date", length = 30)
	public String getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(String modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "Event_DESC", length = 65535)
	public String getEventDesc() {
		return this.eventDesc;
	}

	public void setEventDesc(String eventDesc) {
		this.eventDesc = eventDesc;
	}

	@Column(name = "Rule_DESC", length = 65535)
	public String getRuleDesc() {
		return this.ruleDesc;
	}

	public void setRuleDesc(String ruleDesc) {
		this.ruleDesc = ruleDesc;
	}

	@Column(name = "Report_DESC", length = 65535)
	public String getReportDesc() {
		return this.reportDesc;
	}

	public void setReportDesc(String reportDesc) {
		this.reportDesc = reportDesc;
	}

	@Column(name = "FileURL", length = 65535)
	public String getFileUrl() {
		return this.fileUrl;
	}

	public void setFileUrl(String fileUrl) {
		this.fileUrl = fileUrl;
	}

	@Column(name = "Note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Create_Time",length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(" [");
		buffer.append("logId").append("='").append(getLogId()).append("' ");
		buffer.append("modifyEmp").append("='").append(getModifyEmp())
				.append("' ");
		buffer.append("modifyDate").append("='").append(getModifyDate())
				.append("' ");
		buffer.append("eventDesc").append("='").append(getEventDesc())
				.append("' ");
		buffer.append("ruleDesc").append("='").append(getRuleDesc())
				.append("' ");
		buffer.append("reportDesc").append("='").append(getReportDesc())
				.append("' ");
		buffer.append("fileUrl").append("='").append(getFileUrl()).append("' ");
		buffer.append("note").append("='").append(getNote()).append("' ");
		buffer.append("createTime").append("='").append(getCreateTime())
				.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}
