package com.ynswet.system.sc.domain;
// Generated 2015-6-12 13:37:56 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orggroup generated by hbm2java
 */
@Entity
@Table(name = "orggroup", catalog = "d1")
public class Orggroup implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	/**
	 * 机构内码(人工编码).
	 */
	private Integer orggroupId;

	/**
	 * 机构名称.
	 */
	private String orggroupName;

	/**
	 * 机构类型(*, 见表头定义).
	 */
	private String orggroupType;

	/**
	 * 父记录ID.
	 */
	private Integer parentId;

	/**
	 * 机构级别(0=缺省的最高, 记录从第1级开始, 1=1级).
	 */
	private Integer treeLevel;

	/**
	 * 是否有子节点的标志(*, open=无子节点, closed=有子节点).
	 */
	private String state;

	/**
	 * 启用日期(临时组织必填).
	 */
	private Date openDate;

	/**
	 * 停用日期(临时组织必填).
	 */
	private Date closeDate;

	/**
	 * 状态(*, 0=正常, S=失效).
	 */
	private String status;

	/**
	 * 备注.
	 */
	private String note;

	/**
	 * 记录建立时间.
	 */
	private Date createTime;

	/**
	 * 最后修改时间.
	 */
	private Date modifyTime;

	public Orggroup() {
	}

	public Orggroup(Integer orggroupId, String orggroupName, String orggroupType,
			Integer parentId, Integer treeLevel, String state, String status,
			Date createTime, Date modifyTime) {
		this.orggroupId = orggroupId;
		this.orggroupName = orggroupName;
		this.orggroupType = orggroupType;
		this.parentId = parentId;
		this.treeLevel = treeLevel;
		this.state = state;
		this.status = status;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
	}
	public Orggroup(Integer orggroupId, String orggroupName, String orggroupType,
			Integer parentId, Integer treeLevel, String state, Date openDate,
			Date closeDate, String status, String note, Date createTime,
			Date modifyTime) {
		this.orggroupId = orggroupId;
		this.orggroupName = orggroupName;
		this.orggroupType = orggroupType;
		this.parentId = parentId;
		this.treeLevel = treeLevel;
		this.state = state;
		this.openDate = openDate;
		this.closeDate = closeDate;
		this.status = status;
		this.note = note;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
	}

	@Id
	@Column(name = "ORGGroupID", unique = true, nullable = false)
	public Integer getOrggroupId() {
		return this.orggroupId;
	}

	public void setOrggroupId(Integer orggroupId) {
		this.orggroupId = orggroupId;
	}

	@Column(name = "ORGGroup_Name", nullable = false, length = 100)
	public String getOrggroupName() {
		return this.orggroupName;
	}

	public void setOrggroupName(String orggroupName) {
		this.orggroupName = orggroupName;
	}

	@Column(name = "ORGGroup_Type", nullable = false, length = 1)
	public String getOrggroupType() {
		return this.orggroupType;
	}

	public void setOrggroupType(String orggroupType) {
		this.orggroupType = orggroupType;
	}

	@Column(name = "ParentID", nullable = false)
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Column(name = "Tree_Level", nullable = false)
	public Integer getTreeLevel() {
		return this.treeLevel;
	}

	public void setTreeLevel(Integer treeLevel) {
		this.treeLevel = treeLevel;
	}

	@Column(name = "State", nullable = false, length = 30)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Open_Date", length = 10)
	public Date getOpenDate() {
		return this.openDate;
	}

	public void setOpenDate(Date openDate) {
		this.openDate = openDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Close_Date", length = 10)
	public Date getCloseDate() {
		return this.closeDate;
	}

	public void setCloseDate(Date closeDate) {
		this.closeDate = closeDate;
	}

	@Column(name = "Status", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "Note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Create_Time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Modify_Time", nullable = false, length = 19)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(" [");
		buffer.append("orggroupId").append("='").append(getOrggroupId())
				.append("' ");
		buffer.append("orggroupName").append("='").append(getOrggroupName())
				.append("' ");
		buffer.append("orggroupType").append("='").append(getOrggroupType())
				.append("' ");
		buffer.append("parentId").append("='").append(getParentId())
				.append("' ");
		buffer.append("treeLevel").append("='").append(getTreeLevel())
				.append("' ");
		buffer.append("state").append("='").append(getState()).append("' ");
		buffer.append("openDate").append("='").append(getOpenDate())
				.append("' ");
		buffer.append("closeDate").append("='").append(getCloseDate())
				.append("' ");
		buffer.append("status").append("='").append(getStatus()).append("' ");
		buffer.append("note").append("='").append(getNote()).append("' ");
		buffer.append("createTime").append("='").append(getCreateTime())
				.append("' ");
		buffer.append("modifyTime").append("='").append(getModifyTime())
				.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}
