package com.ynswet.system.sc.domain;
// Generated 2015-7-17 16:03:34 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrgRes generated by hbm2java
 */
@Entity
@Table(name = "org_res", catalog = "fd_d1")
public class OrgRes implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	/**
	 * 组织内码(取自 ORGID表).
	 */
	/**
	 * 资源内码(取自 Res表).
	 */
	private OrgResId id;

	/**
	 * 备注.
	 */
	private String note;

	/**
	 * 记录建立时间.
	 */
	private Date createTime;

	public OrgRes() {
	}

	public OrgRes(OrgResId id, Date createTime) {
		this.id = id;
		this.createTime = createTime;
	}
	public OrgRes(OrgResId id, String note, Date createTime) {
		this.id = id;
		this.note = note;
		this.createTime = createTime;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "orgid", column = @Column(name = "ORGID", nullable = false)),
			@AttributeOverride(name = "resId", column = @Column(name = "ResID", nullable = false))})
	public OrgResId getId() {
		return this.id;
	}

	public void setId(OrgResId id) {
		this.id = id;
	}

	@Column(name = "Note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Create_Time",length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("note").append("='").append(getNote()).append("' ");
		buffer.append("createTime").append("='").append(getCreateTime())
				.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}
