package com.ynswet.system.sc.domain;
// Generated 2015-7-17 16:03:34 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrgResId generated by hbm2java
 */
@Embeddable
public class OrgResId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	/**
	 * 组织内码(取自 ORGID表).
	 */
	private Integer orgid;

	/**
	 * 资源内码(取自 Res表).
	 */
	private Integer resId;

	public OrgResId() {
	}

	public OrgResId(Integer orgid, Integer resId) {
		this.orgid = orgid;
		this.resId = resId;
	}

	@Column(name = "ORGID", nullable = false)
	public Integer getOrgid() {
		return this.orgid;
	}

	public void setOrgid(Integer orgid) {
		this.orgid = orgid;
	}

	@Column(name = "ResID", nullable = false)
	public Integer getResId() {
		return this.resId;
	}

	public void setResId(Integer resId) {
		this.resId = resId;
	}

	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(" [");
		buffer.append("orgid").append("='").append(getOrgid()).append("' ");
		buffer.append("resId").append("='").append(getResId()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object obj) {
		if ((this == obj))
			return true;
		if ((obj == null))
			return false;
		if (!(obj instanceof OrgResId))
			return false;
		OrgResId castOther = (OrgResId) obj;

		return (this.getOrgid() == castOther.getOrgid())
				&& (this.getResId() == castOther.getResId());
	}

	public int hashCode() {
		Integer result = 17;

		result = 37 * result + this.getOrgid();

		result = 37 * result + this.getResId();

		return result;
	}

}
