package com.ynswet.system.sc.domain;
// Generated 2015-6-12 13:37:56 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Permission generated by hbm2java
 */
@Entity
@Table(name = "permission", catalog = "d1")
public class Permission implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	/**
	 * 权限内码.
	 */
	private Integer permissionId;

	/**
	 * 访问地址(*,取自wordbook，按照访问对象地址类型).
	 */
	private String permissionUrl;

	/**
	 * 访问地址操作权限(*,资源、操作取自wordbook，实例手动填写，按照访问规则进行save组装).
	 */
	private String permissionValue;

	/**
	 * 备注.
	 */
	private String note;

	/**
	 * 记录建立时间.
	 */
	private Date createTime;

	public Permission() {
	}

	public Permission(String permissionValue, Date createTime) {
		this.permissionValue = permissionValue;
		this.createTime = createTime;
	}
	public Permission(String permissionUrl, String permissionValue,
			String note, Date createTime) {
		this.permissionUrl = permissionUrl;
		this.permissionValue = permissionValue;
		this.note = note;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PermissionID", unique = true, nullable = false)
	public Integer getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(Integer permissionId) {
		this.permissionId = permissionId;
	}

	@Column(name = "Permission_Url", length = 65535)
	public String getPermissionUrl() {
		return this.permissionUrl;
	}

	public void setPermissionUrl(String permissionUrl) {
		this.permissionUrl = permissionUrl;
	}

	@Column(name = "Permission_value", nullable = false, length = 100)
	public String getPermissionValue() {
		return this.permissionValue;
	}

	public void setPermissionValue(String permissionValue) {
		this.permissionValue = permissionValue;
	}

	@Column(name = "Note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Create_Time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(" [");
		buffer.append("permissionId").append("='").append(getPermissionId())
				.append("' ");
		buffer.append("permissionUrl").append("='").append(getPermissionUrl())
				.append("' ");
		buffer.append("permissionValue").append("='")
				.append(getPermissionValue()).append("' ");
		buffer.append("note").append("='").append(getNote()).append("' ");
		buffer.append("createTime").append("='").append(getCreateTime())
				.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}
