package com.ynswet.system.sc.domain;
// Generated 2015-6-12 13:37:56 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PostId generated by hbm2java
 */
@Embeddable
public class PostId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	/**
	 * 用户内码(取自 USER表).
	 */
	private Integer uid;

	/**
	 * 组织内码, 所属部门.
	 */
	private Integer orgid;

	/**
	 * 角色编码, 部门职务.
	 */
	private Integer roleId;

	public PostId() {
	}

	public PostId(Integer uid, Integer orgid, Integer roleId) {
		this.uid = uid;
		this.orgid = orgid;
		this.roleId = roleId;
	}

	@Column(name = "UID", nullable = false)
	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	@Column(name = "ORGID", nullable = false)
	public Integer getOrgid() {
		return this.orgid;
	}

	public void setOrgid(Integer orgid) {
		this.orgid = orgid;
	}

	@Column(name = "RoleID", nullable = false)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(" [");
		buffer.append("uid").append("='").append(getUid()).append("' ");
		buffer.append("orgid").append("='").append(getOrgid()).append("' ");
		buffer.append("roleId").append("='").append(getRoleId()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object obj) {
		if ((this == obj))
			return true;
		if ((obj == null))
			return false;
		if (!(obj instanceof PostId))
			return false;
		PostId castOther = (PostId) obj;

		return (this.getUid() == castOther.getUid())
				&& (this.getOrgid() == castOther.getOrgid())
				&& (this.getRoleId() == castOther.getRoleId());
	}

	public int hashCode() {
		Integer result = 17;

		result = 37 * result + this.getUid();

		result = 37 * result + this.getOrgid();

		result = 37 * result + this.getRoleId();

		return result;
	}

}
