package com.ynswet.system.sc.domain;
// Generated 2015-7-17 16:03:34 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Post generated by hbm2java
 */
@Entity
@Table(name = "post", catalog = "fd_d1")
public class Post implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	/**
	 * 用户内码(取自 USER表).
	 */
	/**
	 * 组织内码, 所属部门.
	 */
	/**
	 * 角色编码, 部门职务.
	 */
	private PostId id;

	/**
	 * 状态(*, 0=正常, S=失效).
	 */
	private String status;

	/**
	 * 备注.
	 */
	private String note;

	/**
	 * 记录建立时间.
	 */
	private Date createTime;

	/**
	 * 最后修改时间.
	 */
	private Date modifyTime;

	public Post() {
	}

	public Post(PostId id, String status, Date createTime, Date modifyTime) {
		this.id = id;
		this.status = status;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
	}
	public Post(PostId id, String status, String note, Date createTime,
			Date modifyTime) {
		this.id = id;
		this.status = status;
		this.note = note;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "uid", column = @Column(name = "UID", nullable = false)),
			@AttributeOverride(name = "orgid", column = @Column(name = "ORGID", nullable = false)),
			@AttributeOverride(name = "roleId", column = @Column(name = "RoleID", nullable = false))})
	public PostId getId() {
		return this.id;
	}

	public void setId(PostId id) {
		this.id = id;
	}

	@Column(name = "Status", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "Note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Create_Time",length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Modify_Time",  length = 19)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("status").append("='").append(getStatus()).append("' ");
		buffer.append("note").append("='").append(getNote()).append("' ");
		buffer.append("createTime").append("='").append(getCreateTime())
				.append("' ");
		buffer.append("modifyTime").append("='").append(getModifyTime())
				.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}
