package com.ynswet.system.sc.domain;
// Generated 2015-7-17 16:03:34 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Res generated by hbm2java
 */
@Entity
@Table(name = "res", catalog = "fd_d1")
public class Res implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	/**
	 * 资源内码(自增序号).
	 */
	private Integer resId;

	/**
	 * 资源类型(*,S=服务站资源).
	 */
	private String resType;

	/**
	 * 资源ID(取自 资源类型对应实体的ID，例如Sation的ORGID.
	 */
	private Integer itemId;

	/**
	 * 备注.
	 */
	private String note;

	/**
	 * 记录建立时间.
	 */
	private Date createTime;

	public Res() {
	}

	public Res(String resType, Integer itemId, Date createTime) {
		this.resType = resType;
		this.itemId = itemId;
		this.createTime = createTime;
	}
	public Res(String resType, Integer itemId, String note, Date createTime) {
		this.resType = resType;
		this.itemId = itemId;
		this.note = note;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ResID", unique = true, nullable = false)
	public Integer getResId() {
		return this.resId;
	}

	public void setResId(Integer resId) {
		this.resId = resId;
	}

	@Column(name = "Res_Type", nullable = false, length = 1)
	public String getResType() {
		return this.resType;
	}

	public void setResType(String resType) {
		this.resType = resType;
	}

	@Column(name = "ItemID", nullable = false)
	public Integer getItemId() {
		return this.itemId;
	}

	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	@Column(name = "Note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Create_Time",length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(" [");
		buffer.append("resId").append("='").append(getResId()).append("' ");
		buffer.append("resType").append("='").append(getResType()).append("' ");
		buffer.append("itemId").append("='").append(getItemId()).append("' ");
		buffer.append("note").append("='").append(getNote()).append("' ");
		buffer.append("createTime").append("='").append(getCreateTime())
				.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}
