package com.ynswet.system.sc.domain;
// Generated 2015-6-12 13:37:56 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ResL generated by hbm2java
 */
@Entity
@Table(name = "res_l", catalog = "d1")
public class ResL implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	/**
	 * 日志内码(自增序号).
	 */
	private Integer logId;

	/**
	 * 资源内码(取自 Res表).
	 */
	private Integer resId;

	/**
	 * 资源日志类型(*,C=权限建立, M=权限模块).
	 */
	private String resLogType;

	/**
	 * 用户内码(取自 USER表,当前操作人).
	 */
	private Integer modifyUid;

	/**
	 * 日志描述.
	 */
	private String logDesc;

	/**
	 * 记录建立时间.
	 */
	private Date createTime;

	public ResL() {
	}

	public ResL(Integer resId, Integer modifyUid, Date createTime) {
		this.resId = resId;
		this.modifyUid = modifyUid;
		this.createTime = createTime;
	}
	public ResL(Integer resId, String resLogType, Integer modifyUid, String logDesc,
			Date createTime) {
		this.resId = resId;
		this.resLogType = resLogType;
		this.modifyUid = modifyUid;
		this.logDesc = logDesc;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "LogID", unique = true, nullable = false)
	public Integer getLogId() {
		return this.logId;
	}

	public void setLogId(Integer logId) {
		this.logId = logId;
	}

	@Column(name = "ResID", nullable = false)
	public Integer getResId() {
		return this.resId;
	}

	public void setResId(Integer resId) {
		this.resId = resId;
	}

	@Column(name = "ResLog_Type", length = 1)
	public String getResLogType() {
		return this.resLogType;
	}

	public void setResLogType(String resLogType) {
		this.resLogType = resLogType;
	}

	@Column(name = "Modify_UID", nullable = false)
	public Integer getModifyUid() {
		return this.modifyUid;
	}

	public void setModifyUid(Integer modifyUid) {
		this.modifyUid = modifyUid;
	}

	@Column(name = "Log_DESC", length = 65535)
	public String getLogDesc() {
		return this.logDesc;
	}

	public void setLogDesc(String logDesc) {
		this.logDesc = logDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Create_Time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(" [");
		buffer.append("logId").append("='").append(getLogId()).append("' ");
		buffer.append("resId").append("='").append(getResId()).append("' ");
		buffer.append("resLogType").append("='").append(getResLogType())
				.append("' ");
		buffer.append("modifyUid").append("='").append(getModifyUid())
				.append("' ");
		buffer.append("logDesc").append("='").append(getLogDesc()).append("' ");
		buffer.append("createTime").append("='").append(getCreateTime())
				.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}
