package com.ynswet.system.sc.domain;
// Generated 2015-7-17 16:03:34 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "d1")
public class Role implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	/**
	 * 角色编码.
	 */
	private Integer roleId;

	/**
	 * 角色编码(人工编写).
	 */
	private String roleCode;

	/**
	 * 角色名称.
	 */
	private String roleName;

	/**
	 * 角色类型(*, M=经理, E=员工, P=外部员工).
	 */
	private String roleType;

	/**
	 * 主页ID.
	 */
	private Integer homepageId;

	/**
	 * 状态(*, 0=正常, S=失效).
	 */
	private String status;

	/**
	 * 备注.
	 */
	private String note;

	/**
	 * 记录建立时间.
	 */
	private Date createTime;

	/**
	 * 最后修改时间.
	 */
	private Date modifyTime;

	public Role() {
	}

	public Role(String roleCode, String roleName, String roleType,
			Integer homepageId, String status, Date createTime, Date modifyTime) {
		this.roleCode = roleCode;
		this.roleName = roleName;
		this.roleType = roleType;
		this.homepageId = homepageId;
		this.status = status;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
	}
	public Role(String roleCode, String roleName, String roleType,
			Integer homepageId, String status, String note, Date createTime,
			Date modifyTime) {
		this.roleCode = roleCode;
		this.roleName = roleName;
		this.roleType = roleType;
		this.homepageId = homepageId;
		this.status = status;
		this.note = note;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "RoleID", unique = true, nullable = false)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "Role_Code", nullable = false, length = 30)
	public String getRoleCode() {
		return this.roleCode;
	}

	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	@Column(name = "Role_Name", nullable = false, length = 100)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "Role_Type", nullable = false, length = 1)
	public String getRoleType() {
		return this.roleType;
	}

	public void setRoleType(String roleType) {
		this.roleType = roleType;
	}

	@Column(name = "HomepageID", nullable = false)
	public Integer getHomepageId() {
		return this.homepageId;
	}

	public void setHomepageId(Integer homepageId) {
		this.homepageId = homepageId;
	}

	@Column(name = "Status", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "Note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Create_Time",length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Modify_Time",  length = 19)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(" [");
		buffer.append("roleId").append("='").append(getRoleId()).append("' ");
		buffer.append("roleCode").append("='").append(getRoleCode())
				.append("' ");
		buffer.append("roleName").append("='").append(getRoleName())
				.append("' ");
		buffer.append("roleType").append("='").append(getRoleType())
				.append("' ");
		buffer.append("homepageId").append("='").append(getHomepageId())
				.append("' ");
		buffer.append("status").append("='").append(getStatus()).append("' ");
		buffer.append("note").append("='").append(getNote()).append("' ");
		buffer.append("createTime").append("='").append(getCreateTime())
				.append("' ");
		buffer.append("modifyTime").append("='").append(getModifyTime())
				.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}
