package com.ynswet.system.sc.domain;
// Generated 2015-7-17 16:03:34 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RoleMenu generated by hbm2java
 */
@Entity
@Table(name = "role_menu", catalog = "fd_d1")
public class RoleMenu implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	/**
	 * 角色编码(取自 Role表）.
	 */
	/**
	 * 菜单内码(取自 Role_Menu表）.
	 */
	private RoleMenuId id;

	/**
	 * 备注.
	 */
	private String note;

	/**
	 * 记录建立时间.
	 */
	private Date createTime;

	public RoleMenu() {
	}

	public RoleMenu(RoleMenuId id, Date createTime) {
		this.id = id;
		this.createTime = createTime;
	}
	public RoleMenu(RoleMenuId id, String note, Date createTime) {
		this.id = id;
		this.note = note;
		this.createTime = createTime;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "roleId", column = @Column(name = "RoleID", nullable = false)),
			@AttributeOverride(name = "menuId", column = @Column(name = "MenuID", nullable = false))})
	public RoleMenuId getId() {
		return this.id;
	}

	public void setId(RoleMenuId id) {
		this.id = id;
	}

	@Column(name = "Note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Create_Time",length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("note").append("='").append(getNote()).append("' ");
		buffer.append("createTime").append("='").append(getCreateTime())
				.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}
