package com.ynswet.system.sc.domain;
// Generated 2015-7-17 16:03:34 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RoleMenuId generated by hbm2java
 */
@Embeddable
public class RoleMenuId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	/**
	 * 角色编码(取自 Role表）.
	 */
	private Integer roleId;

	/**
	 * 菜单内码(取自 Role_Menu表）.
	 */
	private Integer menuId;

	public RoleMenuId() {
	}

	public RoleMenuId(Integer roleId, Integer menuId) {
		this.roleId = roleId;
		this.menuId = menuId;
	}

	@Column(name = "RoleID", nullable = false)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "MenuID", nullable = false)
	public Integer getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(" [");
		buffer.append("roleId").append("='").append(getRoleId()).append("' ");
		buffer.append("menuId").append("='").append(getMenuId()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object obj) {
		if ((this == obj))
			return true;
		if ((obj == null))
			return false;
		if (!(obj instanceof RoleMenuId))
			return false;
		RoleMenuId castOther = (RoleMenuId) obj;

		return (this.getRoleId() == castOther.getRoleId())
				&& (this.getMenuId() == castOther.getMenuId());
	}

	public int hashCode() {
		Integer result = 17;

		result = 37 * result + this.getRoleId();

		result = 37 * result + this.getMenuId();

		return result;
	}

}
