package com.ynswet.system.sc.domain;
// Generated 2015-7-17 16:03:34 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StationR generated by hbm2java
 */
@Entity
@Table(name = "station_r", catalog = "fd_d1")
public class StationR implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	/**
	 * 组织内码.
	 */
	/**
	 * 关联组织内码.
	 */
	private StationRId id;

	/**
	 * 服务站类型(*, 1=110警察局, 2=120救援, 9=119火警, R=零售商家, L=物流商家, F=餐饮商家).
	 */
	private String stationType;

	/**
	 * 记录建立时间.
	 */
	private Date createTime;

	public StationR() {
	}

	public StationR(StationRId id, String stationType, Date createTime) {
		this.id = id;
		this.stationType = stationType;
		this.createTime = createTime;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "orgid", column = @Column(name = "ORGID", nullable = false)),
			@AttributeOverride(name = "ROrgid", column = @Column(name = "R_ORGID", nullable = false))})
	public StationRId getId() {
		return this.id;
	}

	public void setId(StationRId id) {
		this.id = id;
	}

	@Column(name = "Station_Type", nullable = false, length = 1)
	public String getStationType() {
		return this.stationType;
	}

	public void setStationType(String stationType) {
		this.stationType = stationType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Create_Time",length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("stationType").append("='").append(getStationType())
				.append("' ");
		buffer.append("createTime").append("='").append(getCreateTime())
				.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}
