package com.ynswet.system.sc.domain;
// Generated 2015-7-17 16:03:34 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StationRId generated by hbm2java
 */
@Embeddable
public class StationRId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	/**
	 * 组织内码.
	 */
	private Integer orgid;

	/**
	 * 关联组织内码.
	 */
	private Integer ROrgid;

	public StationRId() {
	}

	public StationRId(Integer orgid, Integer ROrgid) {
		this.orgid = orgid;
		this.ROrgid = ROrgid;
	}

	@Column(name = "ORGID", nullable = false)
	public Integer getOrgid() {
		return this.orgid;
	}

	public void setOrgid(Integer orgid) {
		this.orgid = orgid;
	}

	@Column(name = "R_ORGID", nullable = false)
	public Integer getROrgid() {
		return this.ROrgid;
	}

	public void setROrgid(Integer ROrgid) {
		this.ROrgid = ROrgid;
	}

	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(" [");
		buffer.append("orgid").append("='").append(getOrgid()).append("' ");
		buffer.append("ROrgid").append("='").append(getROrgid()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object obj) {
		if ((this == obj))
			return true;
		if ((obj == null))
			return false;
		if (!(obj instanceof StationRId))
			return false;
		StationRId castOther = (StationRId) obj;

		return (this.getOrgid() == castOther.getOrgid())
				&& (this.getROrgid() == castOther.getROrgid());
	}

	public int hashCode() {
		Integer result = 17;

		result = 37 * result + this.getOrgid();

		result = 37 * result + this.getROrgid();

		return result;
	}

}
