package com.ynswet.system.sc.domain;
// Generated 2015-7-17 16:03:34 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Station generated by hbm2java
 */
@Entity
@Table(name = "station", catalog = "d1")
public class Station implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	/**
	 * 组织内码.
	 */
	private Integer orgid;

	/**
	 * 服务站编号.
	 */
	private String stationNo;

	/**
	 * 服务站名称.
	 */
	private String stationName;

	/**
	 * 服务站类型(*, 0=内部服务站, 1=110警察局, 2=120救援, 9=119火警, R=零售商家, L=物流商家, F=餐饮商家).
	 */
	private String stationType;

	/**
	 * 服务站描述.
	 */
	private String stationDesc;

	/**
	 * 服务站地址.
	 */
	private String stationAdd;

	/**
	 * 服务站电话.
	 */
	private String stationTel;

	/**
	 * 服务站负责人.
	 */
	private String stationLeader;

	/**
	 * 服务站负责人手机.
	 */
	private String leaderCell;

	/**
	 * 服务站级别.
	 */
	private Integer stationLevel;

	/**
	 * 服务站面积.
	 */
	private Integer stationArea;

	/**
	 * 服务站人员数量.
	 */
	private Integer stationPCount;

	/**
	 * 服务站座席数量.
	 */
	private Integer stationSCount;

	/**
	 * 经度.
	 */
	private BigDecimal longitude;

	/**
	 * 纬度.
	 */
	private BigDecimal latitude;

	/**
	 * 状态(*, 0=正常, S=失效).
	 */
	private String status;

	/**
	 * 备注.
	 */
	private String note;

	/**
	 * 记录建立时间.
	 */
	private Date createTime;

	/**
	 * 最后修改时间.
	 */
	private Date modifyTime;

	public Station() {
	}

	public Station(Integer orgid, String stationNo, String stationName,
			String stationType, String stationAdd, String stationTel,
			String stationLeader, String leaderCell, Integer stationLevel,
			Integer stationArea, Integer stationPCount, Integer stationSCount,
			String status, Date createTime, Date modifyTime) {
		this.orgid = orgid;
		this.stationNo = stationNo;
		this.stationName = stationName;
		this.stationType = stationType;
		this.stationAdd = stationAdd;
		this.stationTel = stationTel;
		this.stationLeader = stationLeader;
		this.leaderCell = leaderCell;
		this.stationLevel = stationLevel;
		this.stationArea = stationArea;
		this.stationPCount = stationPCount;
		this.stationSCount = stationSCount;
		this.status = status;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
	}
	public Station(Integer orgid, String stationNo, String stationName,
			String stationType, String stationDesc, String stationAdd,
			String stationTel, String stationLeader, String leaderCell,
			Integer stationLevel, Integer stationArea, Integer stationPCount,
			Integer stationSCount, BigDecimal longitude, BigDecimal latitude,
			String status, String note, Date createTime, Date modifyTime) {
		this.orgid = orgid;
		this.stationNo = stationNo;
		this.stationName = stationName;
		this.stationType = stationType;
		this.stationDesc = stationDesc;
		this.stationAdd = stationAdd;
		this.stationTel = stationTel;
		this.stationLeader = stationLeader;
		this.leaderCell = leaderCell;
		this.stationLevel = stationLevel;
		this.stationArea = stationArea;
		this.stationPCount = stationPCount;
		this.stationSCount = stationSCount;
		this.longitude = longitude;
		this.latitude = latitude;
		this.status = status;
		this.note = note;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
	}

	@Id
	@Column(name = "ORGID", unique = true, nullable = false)
	public Integer getOrgid() {
		return this.orgid;
	}

	public void setOrgid(Integer orgid) {
		this.orgid = orgid;
	}

	@Column(name = "Station_No", nullable = false, length = 30)
	public String getStationNo() {
		return this.stationNo;
	}

	public void setStationNo(String stationNo) {
		this.stationNo = stationNo;
	}

	@Column(name = "Station_Name", nullable = false, length = 100)
	public String getStationName() {
		return this.stationName;
	}

	public void setStationName(String stationName) {
		this.stationName = stationName;
	}

	@Column(name = "Station_Type", nullable = false, length = 1)
	public String getStationType() {
		return this.stationType;
	}

	public void setStationType(String stationType) {
		this.stationType = stationType;
	}

	@Column(name = "Station_DESC", length = 65535)
	public String getStationDesc() {
		return this.stationDesc;
	}

	public void setStationDesc(String stationDesc) {
		this.stationDesc = stationDesc;
	}

	@Column(name = "Station_Add", nullable = false, length = 100)
	public String getStationAdd() {
		return this.stationAdd;
	}

	public void setStationAdd(String stationAdd) {
		this.stationAdd = stationAdd;
	}

	@Column(name = "Station_Tel", nullable = false, length = 30)
	public String getStationTel() {
		return this.stationTel;
	}

	public void setStationTel(String stationTel) {
		this.stationTel = stationTel;
	}

	@Column(name = "Station_Leader", nullable = false, length = 30)
	public String getStationLeader() {
		return this.stationLeader;
	}

	public void setStationLeader(String stationLeader) {
		this.stationLeader = stationLeader;
	}

	@Column(name = "Leader_Cell", nullable = false, length = 30)
	public String getLeaderCell() {
		return this.leaderCell;
	}

	public void setLeaderCell(String leaderCell) {
		this.leaderCell = leaderCell;
	}

	@Column(name = "Station_Level", nullable = false)
	public Integer getStationLevel() {
		return this.stationLevel;
	}

	public void setStationLevel(Integer stationLevel) {
		this.stationLevel = stationLevel;
	}

	@Column(name = "Station_Area", nullable = false)
	public Integer getStationArea() {
		return this.stationArea;
	}

	public void setStationArea(Integer stationArea) {
		this.stationArea = stationArea;
	}

	@Column(name = "Station_P_Count", nullable = false)
	public Integer getStationPCount() {
		return this.stationPCount;
	}

	public void setStationPCount(Integer stationPCount) {
		this.stationPCount = stationPCount;
	}

	@Column(name = "Station_S_Count", nullable = false)
	public Integer getStationSCount() {
		return this.stationSCount;
	}

	public void setStationSCount(Integer stationSCount) {
		this.stationSCount = stationSCount;
	}

	@Column(name = "Longitude", precision = 8, scale = 5)
	public BigDecimal getLongitude() {
		return this.longitude;
	}

	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

	@Column(name = "Latitude", precision = 8, scale = 5)
	public BigDecimal getLatitude() {
		return this.latitude;
	}

	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	@Column(name = "Status", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "Note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Create_Time",length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Modify_Time",  length = 19)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(" [");
		buffer.append("orgid").append("='").append(getOrgid()).append("' ");
		buffer.append("stationNo").append("='").append(getStationNo())
				.append("' ");
		buffer.append("stationName").append("='").append(getStationName())
				.append("' ");
		buffer.append("stationType").append("='").append(getStationType())
				.append("' ");
		buffer.append("stationDesc").append("='").append(getStationDesc())
				.append("' ");
		buffer.append("stationAdd").append("='").append(getStationAdd())
				.append("' ");
		buffer.append("stationTel").append("='").append(getStationTel())
				.append("' ");
		buffer.append("stationLeader").append("='").append(getStationLeader())
				.append("' ");
		buffer.append("leaderCell").append("='").append(getLeaderCell())
				.append("' ");
		buffer.append("stationLevel").append("='").append(getStationLevel())
				.append("' ");
		buffer.append("stationArea").append("='").append(getStationArea())
				.append("' ");
		buffer.append("stationPCount").append("='").append(getStationPCount())
				.append("' ");
		buffer.append("stationSCount").append("='").append(getStationSCount())
				.append("' ");
		buffer.append("longitude").append("='").append(getLongitude())
				.append("' ");
		buffer.append("latitude").append("='").append(getLatitude())
				.append("' ");
		buffer.append("status").append("='").append(getStatus()).append("' ");
		buffer.append("note").append("='").append(getNote()).append("' ");
		buffer.append("createTime").append("='").append(getCreateTime())
				.append("' ");
		buffer.append("modifyTime").append("='").append(getModifyTime())
				.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}
