package com.ynswet.system.sc.domain;
// Generated 2015-6-12 13:37:56 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserloginL generated by hbm2java
 */
@Entity
@Table(name = "userlogin_l", catalog = "d1")
public class UserloginL implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	/**
	 * 日志内码(自增序号).
	 */
	private Integer logId;

	/**
	 * 用户内码.
	 */
	private Integer uid;

	/**
	 * 登录识别串, 登录行为时要记录.
	 */
	private String loginString;

	/**
	 * 登录日志类型（L=登录, Q=退出, P=重要行为).
	 */
	private String loginLogType;

	/**
	 * 日志描述.
	 */
	private String logDesc;

	/**
	 * 记录建立时间.
	 */
	private Date createTime;

	public UserloginL() {
	}

	public UserloginL(Integer uid, Date createTime) {
		this.uid = uid;
		this.createTime = createTime;
	}
	public UserloginL(Integer uid, String loginString, String loginLogType,
			String logDesc, Date createTime) {
		this.uid = uid;
		this.loginString = loginString;
		this.loginLogType = loginLogType;
		this.logDesc = logDesc;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "LogID", unique = true, nullable = false)
	public Integer getLogId() {
		return this.logId;
	}

	public void setLogId(Integer logId) {
		this.logId = logId;
	}

	@Column(name = "UID", nullable = false)
	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	@Column(name = "LoginString", length = 100)
	public String getLoginString() {
		return this.loginString;
	}

	public void setLoginString(String loginString) {
		this.loginString = loginString;
	}

	@Column(name = "LoginLog_Type", length = 1)
	public String getLoginLogType() {
		return this.loginLogType;
	}

	public void setLoginLogType(String loginLogType) {
		this.loginLogType = loginLogType;
	}

	@Column(name = "Log_DESC", length = 65535)
	public String getLogDesc() {
		return this.logDesc;
	}

	public void setLogDesc(String logDesc) {
		this.logDesc = logDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Create_Time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(" [");
		buffer.append("logId").append("='").append(getLogId()).append("' ");
		buffer.append("uid").append("='").append(getUid()).append("' ");
		buffer.append("loginString").append("='").append(getLoginString())
				.append("' ");
		buffer.append("loginLogType").append("='").append(getLoginLogType())
				.append("' ");
		buffer.append("logDesc").append("='").append(getLogDesc()).append("' ");
		buffer.append("createTime").append("='").append(getCreateTime())
				.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}
