package com.ynswet.system.sc.domain;
// Generated 2015-7-17 16:03:34 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Userlogin generated by hbm2java
 */
@Entity
@Table(name = "userlogin", catalog = "fd_d1")
public class Userlogin implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	/**
	 * 登录识别串, 由User表填加, 包括身份证, 电话, 邮箱等.
	 */
	private String loginString;

	/**
	 * 用户内码.
	 */
	private Integer uid;

	/**
	 * 加密的登录密码.
	 */
	private String password;

	/**
	 * 加密盐.
	 */
	private String salt;

	/**
	 * 状态(冗余, *, 0=正常, S=失效).
	 */
	private String status;

	public Userlogin() {
	}

	public Userlogin(String loginString, String password, String salt,
			String status) {
		this.loginString = loginString;
		this.password = password;
		this.salt = salt;
		this.status = status;
	}
	public Userlogin(String loginString, Integer uid, String password,
			String salt, String status) {
		this.loginString = loginString;
		this.uid = uid;
		this.password = password;
		this.salt = salt;
		this.status = status;
	}

	@Id
	@Column(name = "LoginString", unique = true, nullable = false, length = 100)
	public String getLoginString() {
		return this.loginString;
	}

	public void setLoginString(String loginString) {
		this.loginString = loginString;
	}

	@Column(name = "UID")
	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	@Column(name = "Password", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "Salt", nullable = false, length = 100)
	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	@Column(name = "Status", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(" [");
		buffer.append("loginString").append("='").append(getLoginString())
				.append("' ");
		buffer.append("uid").append("='").append(getUid()).append("' ");
		buffer.append("password").append("='").append(getPassword())
				.append("' ");
		buffer.append("salt").append("='").append(getSalt()).append("' ");
		buffer.append("status").append("='").append(getStatus()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}
